//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dbsys.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        public Movie()
        {
            this.Showtimes = new HashSet<Showtimes>();
        }
    
        public int movieId { get; set; }
        public string movieName { get; set; }
        public int moviePrice { get; set; }
        public int movieReleaseYear { get; set; }
        public string movieGenre { get; set; }
        public string movieDirector { get; set; }
        public string moviePublisher { get; set; }
        public string moviePathImg { get; set; }
    
        public virtual ICollection<Showtimes> Showtimes { get; set; }
    }
}
