//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dbsys.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        public int salesID { get; set; }
        public Nullable<int> ticketID { get; set; }
        public int transactionAmount { get; set; }
        public System.DateTime transactionDate { get; set; }
        public System.TimeSpan transactionTime { get; set; }
    
        public virtual Tickets Tickets { get; set; }
    }
}
