//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dbsys.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_TransactionHistory
    {
        public int saleID { get; set; }
        public Nullable<int> showtimeID { get; set; }
        public Nullable<int> movieID { get; set; }
        public string movieName { get; set; }
        public string customerName { get; set; }
        public System.DateTime transactionDate { get; set; }
        public int seatNumber { get; set; }
        public int quantity { get; set; }
        public decimal totalAmount { get; set; }
        public decimal paidAmount { get; set; }
        public decimal changeAmount { get; set; }
    }
}
